[project]
name = "sk-learn-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "scikit-learn>=1.7.0",
    "seaborn>=0.13.2",
]
